# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AIS(object):
    def setupUi(self, AIS):
        AIS.setObjectName("AIS")
        AIS.setEnabled(True)
        AIS.resize(1100, 752)
        AIS.setMinimumSize(QtCore.QSize(0, 0))
        AIS.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(AIS)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1081, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LabelSearchTextToolTip = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSearchTextToolTip.sizePolicy().hasHeightForWidth())
        self.LabelSearchTextToolTip.setSizePolicy(sizePolicy)
        self.LabelSearchTextToolTip.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LabelSearchTextToolTip.setFont(font)
        self.LabelSearchTextToolTip.setLineWidth(1)
        self.LabelSearchTextToolTip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.LabelSearchTextToolTip.setObjectName("LabelSearchTextToolTip")
        self.verticalLayout.addWidget(self.LabelSearchTextToolTip)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineSub = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LineSub.setMaximumSize(QtCore.QSize(30, 16777215))
        self.LineSub.setMaxLength(2)
        self.LineSub.setObjectName("LineSub")
        self.horizontalLayout.addWidget(self.LineSub)
        self.LineRay = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LineRay.setMaximumSize(QtCore.QSize(30, 16777215))
        self.LineRay.setMaxLength(2)
        self.LineRay.setObjectName("LineRay")
        self.horizontalLayout.addWidget(self.LineRay)
        self.LineKva = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LineKva.setMaximumSize(QtCore.QSize(75, 16777215))
        self.LineKva.setText("")
        self.LineKva.setMaxLength(6)
        self.LineKva.setObjectName("LineKva")
        self.horizontalLayout.addWidget(self.LineKva)
        self.LineObn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LineObn.setMaximumSize(QtCore.QSize(180, 16777215))
        self.LineObn.setObjectName("LineObn")
        self.horizontalLayout.addWidget(self.LineObn)
        self.ButtonSearch = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonSearch.setFont(font)
        self.ButtonSearch.setObjectName("ButtonSearch")
        self.horizontalLayout.addWidget(self.ButtonSearch)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ScrollAreaSearchResult = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.ScrollAreaSearchResult.setMaximumSize(QtCore.QSize(413, 16777215))
        self.ScrollAreaSearchResult.setWidgetResizable(True)
        self.ScrollAreaSearchResult.setObjectName("ScrollAreaSearchResult")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 411, 614))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.LabelSearchResult = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.LabelSearchResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.LabelSearchResult.setObjectName("LabelSearchResult")
        self.gridLayout.addWidget(self.LabelSearchResult, 0, 0, 1, 1)
        self.ScrollAreaSearchResult.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.ScrollAreaSearchResult)
        self.ScrollAreaProps = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.ScrollAreaProps.setMaximumSize(QtCore.QSize(690, 16777215))
        self.ScrollAreaProps.setWidgetResizable(True)
        self.ScrollAreaProps.setObjectName("ScrollAreaProps")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 656, 614))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LabelProps = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.LabelProps.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.LabelProps.setObjectName("LabelProps")
        self.gridLayout_2.addWidget(self.LabelProps, 0, 0, 1, 1)
        self.ScrollAreaProps.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.addWidget(self.ScrollAreaProps)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.ButtonExcelExport = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonExcelExport.sizePolicy().hasHeightForWidth())
        self.ButtonExcelExport.setSizePolicy(sizePolicy)
        self.ButtonExcelExport.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ButtonExcelExport.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.ButtonExcelExport.setFont(font)
        self.ButtonExcelExport.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ButtonExcelExport.setObjectName("ButtonExcelExport")
        self.verticalLayout.addWidget(self.ButtonExcelExport)
        AIS.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AIS)
        self.statusbar.setObjectName("statusbar")
        AIS.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(AIS)
        self.action.setObjectName("action")

        self.retranslateUi(AIS)
        QtCore.QMetaObject.connectSlotsByName(AIS)

    def retranslateUi(self, AIS):
        _translate = QtCore.QCoreApplication.translate
        AIS.setWindowTitle(_translate("AIS", "AIS"))
        self.LabelSearchTextToolTip.setText(_translate("AIS", "Поиск по Кадастровому Номеру"))
        self.LineSub.setText(_translate("AIS", "26"))
        self.ButtonSearch.setText(_translate("AIS", "Найти"))
        self.LabelSearchResult.setText(_translate("AIS", "Результат Поиска"))
        self.LabelProps.setText(_translate("AIS", "Характеристики объекта"))
        self.ButtonExcelExport.setText(_translate("AIS", "Экспорт в Excel"))
        self.action.setText(_translate("AIS", "Открыть"))

